name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Get Python version
      run: python -V
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run Python
      run: python sklearn_digits.py
